### ISSUE TITLE
404 on api shutdown call

### ISSUE THREAD

**Issue by HerveMignot** [fcollonval/jupyterlab_quit#1]
Hello,

I have a 404 when clicking on the Quit button, with the following message in the log:
[W 16:46:31.257 LabApp] 404 POST /api/shutdown?1529073991175 (127.0.0.1) 72.01ms referer=http://localhost:8888/lab

This installation of Jupyterlab is running on Win7.
Thank you for any direction to look for.

Hervé

PS: is there a minimum version requirements for jupyter server? This install is 5.0.0.

**Comment by fcollonval** [comment]
Dear Hervé, there is indeed a minimum version for the python package notebook i.e. >=5.1.
Before it, the api/shutdown was not existing. Hence your situation 404 = address not found.
Hope you can update your installation to activate the button.

**Comment by HerveMignot** [comment]
Thank you for this quick answer, that was my best guest, and I am upgrading my version.
